version: '2'

services:
  php:
    build:
        context: ./php7.2
    volumes:
        - docroot:/var/www/html
#        - ./.ssh:/var/www/.ssh
#        - ./php7.2/composer:/usr/local/bin/composer
#        - "nfs-data:/var/www/virtual/obag.pl/htdocs/pub"
#    restart: unless-stopped
  web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
#        - ../code:/var/www/html
#        - docroot:/var/www/html
        - ./nginx/magento.conf:/etc/nginx/conf.d/default.conf
    volumes_from: 
        - php
    links:
        - php

volumes:
  docroot:
    driver: local
#  nfs-data:
#    driver: local
#    driver_opts:
#      type: "nfs"
#      o: "nfsvers=4,addr=s42.mhost.eu,rw"
#      device: ":/var/www/virtual/obag.pl/htdocs/pub"
